apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
      {{#each outbound-access-apps}}
          - application: {{this}}
      {{/each}}
      external:
      {{#each outbound-access-hosts}}
          - host: {{this}}
      {{/each}}
      {{#each outbound-access-kafka-hosts}}
          - host: {{this}}
            ports:
              - name: kafka
                port: 8443
                protocol: TCP
      {{/each}}
  image: {{ image }}
  kafka:
    pool: {{ kafka.pool }}
  liveness:
    path: /bidrag-arbeidsflyt/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-arbeidsflyt/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-arbeidsflyt/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  envFrom:
    - secret: bidrag-arbeidsflyt-secrets
  env:
    - name: OPPGAVE_URL
      value: https://{{ azure.oppgave }}
    - name: BIDRAG_TILGANGSKONTROLL_URL
      value: http://{{ azure.tilgangskontroll }}
    - name: PERSON_URL
      value: https://{{ azure.person }}
    - name: ORGANISASJON_URL
      value: https://{{ azure.organisasjon }}
    - name: BIDRAG_DOKUMENT_URL
      value: https://{{ azure.dokument }}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: {{ kafka.bootstrap_servers }}
    - name: OPPGAVE_SCOPE
      value: {{ azure.oppgave_clientid }}
    - name: PERSON_SCOPE
      value: {{ azure.person_clientid }}
    - name: ORGANISASJON_SCOPE
      value: {{ azure.organisasjon_clientid }}
    - name: DOKUMENT_SCOPE
      value: {{ azure.dokument_clientid }}
    - name: TILGANGSKONTROLL_SCOPE
      value: {{ azure.tilgangskontroll_clientid }}
    - name: TOPIC_JOURNALPOST
      value: {{ kafka-topic-journalpost }}
    - name: TOPIC_OPPGAVE_ENDRET
      value: {{ kafka-topic-oppgave-endret }}
    - name: TOPIC_OPPGAVE_OPPRETTET
      value: {{ kafka-topic-oppgave-opprettet }}
    - name: TOPIC_OPPGAVE_HENDELSE
      value: {{ kafka-topic-oppgave-hendelse }}
    - name: FEATURE_ENABLED
      value: {{ feature-toggle }}
    - name: JAVA_OPTS
      value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005

  gcp:
    sqlInstances:
      - name: {{ database.dbname }}
        type: POSTGRES_14
        diskAutoresize: {{ database.autoResize }}
        databases:
          - name: bidrag-arbeidsflyt-db
            envVarPrefix: DB

