apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: {{ azure.oppgave }}
  image: {{ image }}
  kafka:
    pool: {{ kafka.pool }}
  liveness:
    path: /bidrag-arbeidsflyt/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-arbeidsflyt/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-arbeidsflyt/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  envFrom:
    - secret: bidrag-arbeidsflyt-secrets
  env:
    - name: OPPGAVE_URL
      value: https://{{ azure.oppgave }}
    - name: PERSON_URL
      value: https://{{ azure.person }}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: {{ kafka.bootstrap_servers }}
    - name: OPPGAVE_SCOPE
      value: {{ azure.oppgave_clientid }}
    - name: PERSON_SCOPE
      value: {{ azure.person_clientid }}
    - name: TOPIC_JOURNALPOST
      value: {{ kafka-topic-journalpost }}
    - name: TOPIC_OPPGAVE_ENDRET
      value: {{ kafka-topic-oppgave-endret }}
    - name: TOPIC_OPPGAVE_OPPRETTET
      value: {{ kafka-topic-oppgave-opprettet }}
    - name: FEATURE_ENABLED
      value: {{ feature-toggle }}
  gcp:
    sqlInstances:
      - name: {{ database.dbname }}
        type: POSTGRES_14
        cascadingDelete: true
        diskAutoresize: {{ database.autoResize }}
        databases:
          - name: bidrag-arbeidsflyt-db
            envVarPrefix: DB

