apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  accessPolicy:
    inbound:
      rules:
        - application: {{ access.inbound-rule.bidrag-cucumber-cloud }}
    outbound:
      external:
        - host: {{ access.outbound-external.oppgave }}
  azure:
    application:
      enabled: true
  image: {{ image }}
  kafka:
    pool: {{ kafka.pool }}
  liveness:
    path: /bidrag-arbeidsflyt/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-arbeidsflyt/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-arbeidsflyt/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
    - name: OPPGAVE_URL
      value: https://{{ access.outbound-external.oppgave }}
    - name: TOPIC_JOURNALPOST
      value: {{ kafka-topic-journalpost }}
