apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: {{ azure.oppgave }}
  image: {{ image }}
  kafka:
    pool: {{ kafka.pool }}
  liveness:
    path: /bidrag-arbeidsflyt/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-arbeidsflyt/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-arbeidsflyt/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
    - name: OPPGAVE_URL
      value: https://{{ azure.oppgave }}
    - name: OPPGAVE_SCOPE
      value: {{ azure.oppgave_clientid }}
    - name: TOPIC_JOURNALPOST
      value: {{ kafka-topic-journalpost }}
    - name: ENABLE_EVENTS
      value: {{ enable-events }}
    - name: JAVA_OPTS
      value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
