name: bidrag-arbeidsflyt
kafka:
  pool: nav-prod
min_replicas: 2
cpu:
  limits: 1000m
  requests: 300m
env:
  OPPGAVE_URL: https://oppgave.prod-fss-pub.nais.io
  ORGANISASJON_URL: https://bidrag-organisasjon.prod-fss-pub.nais.io
  PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io
  BIDRAG_DOKUMENT_URL: https://bidrag-dokument.prod-fss-pub.nais.io
  BIDRAG_TILGANGSKONTROLL_URL: http://bidrag-tilgangskontroll

  ORGANISASJON_SCOPE: prod-fss.bidrag.bidrag-organisasjon
  PERSON_SCOPE: prod-fss.bidrag.bidrag-person
  OPPGAVE_SCOPE: prod-fss.oppgavehandtering.oppgave
  DOKUMENT_SCOPE: prod-fss.bidrag.bidrag-dokument
  TILGANGSKONTROLL_SCOPE: prod-gcp.bidrag.bidrag-tilgangskontroll

  TOPIC_OPPGAVE_HENDELSE: oppgavehandtering.oppgavehendelse-v1
  TOPIC_DOKUMENT: bidrag.dokument
  TOPIC_JOURNALPOST: bidrag.journalpost
database:
  dbname: bidrag-arbeidsflyt
  autoResize: true
  tier: db-f1-micro
ingresses:
  - https://bidrag-arbeidsflyt.intern.nav.no
outbound-access-apps:
  - bidrag-tilgangskontroll
outbound-access-hosts:
   - bidrag-dokument.prod-fss-pub.nais.io
   - bidrag-person.prod-fss-pub.nais.io
   - oppgave.prod-fss-pub.nais.io
   - bidrag-organisasjon.prod-fss-pub.nais.io