name: bidrag-arbeidsflyt
azure:
  oppgave: oppgave.prod-fss-pub.nais.io
  oppgave_clientid: prod-fss.oppgavehandtering.oppgave
kafka:
  pool: nav-prod
  bootstrap_servers: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
kafka-topic-journalpost: bidrag.journalpost
kafka-topic-oppgave-endret: aapen-oppgave-endret-v1-prod
kafka-topic-oppgave-opprettet: aapen-oppgave-opprettet-v1-prod
feature-toggle: NONE
database:
  dbname: bidrag-arbeidsflyt-prod
  autoResize: true
ingresses:
  - https://bidrag-arbeidsflyt.intern.nav.no
