server:
  servlet:
    context-path: /bidrag-arbeidsflyt

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"

SERVICE_USER_USERNAME: srvBdArbeidsflyt
SERVICE_USER_PASSWORD: ${SRV_BD_ARBEIDSFLYT_PASSWORD}
KAFKA_GROUP_ID: bidrag-arbeidsflyt-oppgave-consumer

---
spring:
  config:
    activate:
      on-profile: live
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        endpoint.identification.algorithm:
    consumer:
      enableAutoCommit: false
    listener:
      ackMode: RECORD

no.nav.security.jwt:
  client:
    registration:
      oppgave:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${OPPGAVE_SCOPE}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
