AAD_ISSUER_URI: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851

server:
  servlet:
    context-path: /bidrag-arbeidsflyt

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AAD_ISSUER_URI}/v2.0
          accepted-audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}
      client:
        registration:
          bidrag-arbeidsflyt:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: api://a1fd9dc1-2590-4e10-86a1-bc611c96dc17/.default
        provider:
          aad:
            token-uri: ${AAD_ISSUER_URI}/oauth2/v2.0/token
            jwk-set-uri: ${AAD_ISSUER_URI}/discovery/v2.0/keys
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        endpoint.identification.algorithm:
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
