apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-arbeidsflyt
  namespace: bidrag
  labels:
    team: bidrag
spec:
  image: {{ image }}
  kafka:
    pool: nav-prod
  liveness:
    path: /bidrag-arbeidsflyt/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-arbeidsflyt/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-arbeidsflyt/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - https://bidrag-arbeidsflyt.intern.adeo.no
  env:
    - name: TOPIC_JOURNALPOST
      value: bidrag.journalpost
