CREATE TABLE IF NOT EXISTS journalpost (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 CACHE 20 ),
    journalpost_id varchar(20) NOT NULL,
    status varchar(10) NOT NULL,
    opprettet_timestamp timestamp DEFAULT now() NOT NULL,
    CONSTRAINT journalpost_pkey PRIMARY KEY (id)
);

GRANT ALL PRIVILEGES ON TABLE public.journalpost TO cloudsqliamuser;