CREATE TABLE IF NOT EXISTS journalpost (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 CACHE 20 ),
    journalpostId varchar(20) NOT NULL,
    status varchar(10) NOT NULL,
    CONSTRAINT journalpost_pkey PRIMARY KEY (id)
)