CREATE TABLE IF NOT EXISTS journalpost (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 CACHE 20 ),
    journalpost_id varchar(30) NOT NULL,
    tema varchar(20) NOT NULL,
    enhet varchar(20) NOT NULL,
    status varchar(20) NOT NULL,
    opprettet_timestamp timestamp DEFAULT now() NOT NULL,
    endret_timestamp timestamp DEFAULT now() NOT NULL,
    CONSTRAINT journalpost_pkey PRIMARY KEY (id)
);

CREATE TRIGGER update_journalpost_endret BEFORE UPDATE ON journalpost FOR EACH ROW EXECUTE PROCEDURE update_endret_timestamp();

GRANT ALL PRIVILEGES ON TABLE public.journalpost TO cloudsqliamuser;

CREATE INDEX idx_journalpost_id ON journalpost(journalpost_id);