CREATE TABLE IF NOT EXISTS behandling
(
    id                          integer                 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 CACHE 20 ),
    behandlingsid               numeric,
    søknadsid                   numeric,
    oppgave                     jsonb,
    behandles_av_flere_søknader boolean   default false,
    status                      text                    NOT NULL,
    enhet                       text                    NOT NULL,
    barn                        jsonb,
    mottatt_dato                date                    not null,
    norm_dato                   date,
    opprettet_tidspunkt         timestamp DEFAULT now() NOT NULL,
    endret_tidspunkt            timestamp DEFAULT now() NOT NULL
);


CREATE INDEX if not exists idx_gin_behandling_barn ON behandling USING GIN (barn);

CREATE INDEX idx_behandling_behandlingsid ON behandling (behandlingsid);
CREATE INDEX idx_behandling_søknadsid ON behandling (søknadsid);

GRANT ALL PRIVILEGES ON TABLE public.behandling TO cloudsqliamuser;
