CREATE TABLE IF NOT EXISTS dl_kafka (
   id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 CACHE 20 ),
   topic_name varchar(50) NOT NULL,
   message_key varchar(50) NOT NULL,
   payload text NOT NULL,
   opprettet_timestamp timestamp DEFAULT now() NOT NULL,
   retry boolean default false,
   CONSTRAINT dl_kafka_pkey PRIMARY KEY (id)
);

GRANT ALL PRIVILEGES ON TABLE public.dl_kafka TO cloudsqliamuser;

CREATE INDEX idx_dl_kafka_retry ON dl_kafka(retry);
CREATE INDEX idx_dl_kafka_topic ON dl_kafka(topic_name);