name: continuous integration
on:
  push:
    branches:
      - '**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/bidrag-arbeidsflyt:${{ github.sha }}

jobs:

  build:
    name: Build with maven and docker
    runs-on: self-hosted

    steps:
      - uses: navikt/bidrag-docker/local-exists@v1
        id: dockerimage
        with:
          image_id: ${{ env.IMAGE }}
      - run: echo ::set-env name=NOT_FOUND::${{ steps.dockerimage.outputs.not_found }}
      - run: env
      - run: sudo rm -rf *
      - uses: actions/checkout@v2
        if: env.NOT_FOUND == 'true'
      - uses: navikt/bidrag-maven/verify-dependencies@v1
        if: env.NOT_FOUND == 'true'
        with:
          maven_image: maven:3.6.3-openjdk-15
      - run: docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-openjdk-15 mvn install -B -e
        if: env.NOT_FOUND == 'true'
      - name: Build and publish Docker image
        if: env.NOT_FOUND == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
