name: continuous integration
on:
  push:
    branches:
      - '**'
      - '!release'

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:

  build:
    name: Build with maven and docker
    runs-on: ubuntu-latest

    steps:
      - uses: navikt/bidrag-docker/exists@v1
        id: dockerimage
        with:
          image_name: bidrag-arbeidsflyt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo NOT_FOUND=${{ steps.dockerimage.outputs.not_found }} >> $GITHUB_ENV
      - uses: actions/checkout@v2
        if: env.NOT_FOUND == 'true'
      - uses: actions/setup-java@v1
        if: env.NOT_FOUND == 'true'
        with:
          java-version: '17'
      - uses: actions/cache@v1
        if: env.NOT_FOUND == 'true'
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: navikt/bidrag-maven/setup@v7
        if: env.NOT_FOUND == 'true'
        with:
          repositories: maven-central=https://repo.maven.apache.org/maven2,github-packages=https://maven.pkg.github.com/navikt/maven-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: navikt/bidrag-maven/verify-dependencies@v7
        if: env.NOT_FOUND == 'true'
      - run: mvn install -B -e
        if: env.NOT_FOUND == 'true'
      - name: Build and publish Docker image
        if: env.NOT_FOUND == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker image build --tag ${IMAGE} .
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker image push ${IMAGE}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy docker image to dev
    needs: build

    steps:
      - uses: actions/checkout@v2
        with:
          path: deploy
      - name: Deploy main branch to dev-gcp
        if: github.ref != 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/.nais/nais.yaml
          VARS: deploy/.nais/main.yaml
      - name: Deploy feature to dev-gcp
        if: github.ref != 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/.nais/nais.yaml
          VARS: deploy/.nais/feature.yaml

  run-tests-for-opprett-oppgave:
    runs-on: ubuntu-latest
    name: "Run tests: opprett-oppgave"
    needs: deploy

    env:
      INGRESS_OPPGAVE: https://oppgave.dev-fss-pub.nais.io
      INGRESS_CUCUMBER: https://bidrag-cucumber-cloud.ekstern.dev.nav.no

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_OPPGAVE=https://oppgave-q1.dev-fss-pub.nais.io" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"tags":["@arbeidsflyt-opprett-oppgave"],"testUsername":"z992903","noContextPathForApps":["oppgave"],"ingressesForApps":[
                   "${{ env.INGRESS_OPPGAVE }}@oppgave"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-endre-fagomrade:
    runs-on: ubuntu-latest
    name: "Run tests: endre-fagomrade"
    needs: deploy

    env:
      INGRESS_CUCUMBER: https://bidrag-cucumber-cloud.ekstern.dev.nav.no
      INGRESS_OPPGAVE: https://oppgave.dev-fss-pub.nais.io

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_OPPGAVE=https://oppgave-q1.dev-fss-pub.nais.io" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"tags":["@arbeidsflyt-endre-fagomrade"],"testUsername":"z992903","noContextPathForApps":["oppgave"],"ingressesForApps":[
                   "${{ env.INGRESS_OPPGAVE }}@oppgave"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-overfor-enhet:
    runs-on: ubuntu-latest
    name: "Run tests: overfor-til-annen-enhet"
    needs: deploy

    env:
      INGRESS_CUCUMBER: https://bidrag-cucumber-cloud.ekstern.dev.nav.no
      INGRESS_OPPGAVE: https://oppgave.dev-fss-pub.nais.io

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_OPPGAVE=https://oppgave-q1.dev-fss-pub.nais.io" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"tags":["@arbeidsflyt-overfor-til-annen-enhet"],"testUsername":"z992903","noContextPathForApps":["oppgave"],"ingressesForApps":[
                   "${{ env.INGRESS_OPPGAVE }}@oppgave"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  run-tests-for-journalforing:
    runs-on: ubuntu-latest
    name: "Run tests for journalforing"
    needs: deploy

    env:
      INGRESS_CUCUMBER: https://bidrag-cucumber-cloud.ekstern.dev.nav.no
      INGRESS_OPPGAVE: https://oppgave.dev-fss-pub.nais.io

    steps:
      - name: feature ingresses
        if: github.ref != 'refs/heads/main'
        run: |
          echo "INGRESS_OPPGAVE=https://oppgave-q1.dev-fss-pub.nais.io" >> $GITHUB_ENV
          echo "INGRESS_CUCUMBER=https://bidrag-cucumber-cloud-feature.ekstern.dev.nav.no" >> $GITHUB_ENV
      - run: |
          curl -H "Content-Type: application/json" -i \
               --request POST \
               --data '{"tags":["@arbeidsflyt-journalforing"],"testUsername":"z992903","noContextPathForApps":["oppgave"],"ingressesForApps":[
                   "${{ env.INGRESS_OPPGAVE }}@oppgave"
                 ]}' \
               ${{ env.INGRESS_CUCUMBER }}/bidrag-cucumber-cloud/run | tee .cucumber-result
          cat .cucumber-result | grep HTTP/2 | grep -c 200 > /dev/null # fails if count is 0 (http status is not ok, aka http status code is not 200)

  bump_dev_version:
    runs-on: ubuntu-latest
    name: Bump SNAPSHOT version
    if: github.ref == 'refs/heads/main'
    needs:
      - run-tests-for-endre-fagomrade
      - run-tests-for-journalforing
      - run-tests-for-opprett-oppgave
      - run-tests-for-overfor-enhet

    steps:
      - uses: actions/checkout@v2
      - uses: navikt/bidrag-git/tag-snap@v1-tag-snap
